[build-system]
requires = ["setuptools>=45", "wheel", "setuptools_scm[toml]>=6.2"]
build-backend = "setuptools.build_meta"

[project]
name = "app-personal-contact-backend"
version = "1.7.86dev0"
description = "Backend da aplicaÃ§Ã£o de contatos pessoais"
authors = [
    {name = "Hugllas Lima", email = "hugllasLima@gmail.com"}
]
readme = "README.md"
license = {text = "MIT"}
requires-python = ">=3.8"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
]

[tool.commitizen]
name = "cz_conventional_commits"
version = "1.7.86dev0"
changelog_file = "CHANGELOG.md"
changelog_incremental = false
update_changelog_on_bump = true
major_version_zero = false
version_files = [
    "pyproject.toml:version",
    "pyproject.toml:tool.commitizen.version",
    "pyproject.toml:tool.bumpversion.current_version"
]

[tool.commitizen.change_type_map]
feat = "âœ¨ Novas Funcionalidades"
fix = "ğŸ› CorreÃ§Ãµes de Bugs"
docs = "ğŸ“š DocumentaÃ§Ã£o"
style = "ğŸ’ Estilo e FormataÃ§Ã£o"
refactor = "â™»ï¸ RefatoraÃ§Ã£o"
perf = "âš¡ Performance"
test = "ğŸ§ª Testes"
build = "ğŸ”§ Build e CI/CD"
ci = "ğŸ‘· IntegraÃ§Ã£o ContÃ­nua"
chore = "ğŸ”¨ ManutenÃ§Ã£o"
revert = "âª ReversÃµes"

[tool.bumpversion]
current_version = "1.7.86dev0"
commit = true
tag = true
parse = "(?P<major>\\d+)\\.(?P<minor>\\d+)\\.(?P<patch>\\d+)((?P<release>[a-zA-Z]+)(?P<num>\\d+))?"
serialize = [
    "{major}.{minor}.{patch}{release}{num}",
    "{major}.{minor}.{patch}"
]

[[tool.bumpversion.files]]
filename = "pyproject.toml"
search = 'version = "{current_version}"'
replace = 'version = "{new_version}"'

[[tool.bumpversion.files]]
filename = "CHANGELOG.md"
search = "## [Unreleased]"
replace = "## [Unreleased]\n\n## [{new_version}] - {now:%Y-%m-%d}"

[tool.bumpversion.parts.release]
optional_value = "gamma"
values = [
    "dev",
    "alpha", 
    "a",
    "beta",
    "b",
    "rc",
    "gamma"
]

[tool.standard-version]
types = [
    {"type" = "feat", "section" = "âœ¨ Novas Funcionalidades"},
    {"type" = "fix", "section" = "ğŸ› CorreÃ§Ãµes de Bugs"},
    {"type" = "docs", "section" = "ğŸ“š DocumentaÃ§Ã£o"},
    {"type" = "style", "section" = "ğŸ’ Estilo e FormataÃ§Ã£o"},
    {"type" = "refactor", "section" = "â™»ï¸ RefatoraÃ§Ã£o"},
    {"type" = "perf", "section" = "âš¡ Performance"},
    {"type" = "test", "section" = "ğŸ§ª Testes"},
    {"type" = "build", "section" = "ğŸ”§ Build e CI/CD"},
    {"type" = "ci", "section" = "ğŸ‘· IntegraÃ§Ã£o ContÃ­nua"},
    {"type" = "chore", "section" = "ğŸ”¨ ManutenÃ§Ã£o"},
    {"type" = "revert", "section" = "âª ReversÃµes"}
]
